### method
stage: sft
do_train: true
finetuning_type: lora

### lora
lora_rank: 32
lora_alpha: 32
lora_dropout: 0.1
lora_target: "q_proj,k_proj,v_proj,o_proj,gate_proj,up_proj,down_proj"
use_rslora: true


### dataset
dataset: product_angle_train
template: qwen2_vl
cutoff_len: 2048
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: saves/qwen2_5vl-3b/lora/sft
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 2
learning_rate: 5e-5
num_train_epochs: 12.0
lr_scheduler_type: cosine
# warmup_ratio: 0.1
warmup_steps: 20
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
